name: github_viewer
description: Example flutter project.
publish_to: 'none' 
environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.6.0
  flutter_riverpod: ^2.3.0
  flutter_secure_storage: ^7.0.0
  form_builder_companion_presenter: ^0.5.0
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.2.0
  github: ^9.4.0
  go_router: ^6.0.0
  meta: ^1.7.0
  oauth2_client: ^3.1.0
  platform: ^3.1.0
  riverpod_annotation: ^2.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  form_companion_generator: ^0.5.0
  freezed: ^2.2.0
  grinder: ^0.9.2
  path: ^1.8.0
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
