//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubViewer.Localization.Pages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SignIn_Display {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignIn_Display() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHubViewer.Localization.Pages.SignIn.Display", typeof(SignIn_Display).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Client ID configured in your GitHub account setting for this app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientId_Description {
            get {
                return ResourceManager.GetString("ClientId.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientId_Name {
            get {
                return ResourceManager.GetString("ClientId.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client Secret configured in your GitHub account setting for this app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientSecret_Description {
            get {
                return ResourceManager.GetString("ClientSecret.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client Secret に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientSecret_Name {
            get {
                return ResourceManager.GetString("ClientSecret.Name", resourceCulture);
            }
        }
    }
}
